FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm i -g pnpm@8.15.9

COPY . .

RUN pnpm install

RUN pnpm run db:generate

RUN pnpm dlx turbo build --filter=http-backend

EXPOSE 3001

CMD ["pnpm", "run", "start:http"]
