FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm i -g pnpm

COPY . .

RUN pnpm install

RUN pnpm dlx turbo build --filter=http-backend

RUN pnpm run db:generate

EXPOSE 3001

CMD ["pnpm", "run", "start:http"]
