name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ SECRETS.DOCKERHUB_USERNAME }}
          password: ${{ SECRETS.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ SECRETS.DOCKERHUB_USERNAME }}/dexcalidraw-http:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.websocket
          push: true
          tags: ${{ SECRETS.DOCKERHUB_USERNAME }}/dexcalidraw-ws:latest
      - name: SSH and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ SECRETS.GCP_PRIVATE_KEY }}" > ~/.ssh/dexcalidraw-key
          chmod 600 ~/.ssh/dexcalidraw-key
          ssh-keyscan -H ${{ SECRETS.HOST }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/dexcalidraw-key ${{ SECRETS.USERNAME }}@${{ SECRETS.HOST }} "docker-compose up"
